version: '3.8'

services:
  synapcity-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
